26-Jun-19 15:39:54 - Job Started
26-Jun-19 15:39:54 - Creating Excel...
26-Jun-19 15:40:13 - Sending Email...
26-Jun-19 15:40:22 - (535, b'5.7.3 Authentication unsuccessful [BN7PR06CA0002.namprd06.prod.outlook.com]')
Traceback (most recent call last):
  File "D:/Users/User/PycharmProjects/Scheduler/venv/FailedOrder.py", line 82, in sendEmail
    server.login(sender_email, password)
  File "D:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 730, in login
    raise last_exception
  File "D:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "D:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.3 Authentication unsuccessful [BN7PR06CA0002.namprd06.prod.outlook.com]')
26-Jun-19 15:40:23 - Job Completed
26-Jun-19 15:41:23 - Job Started
26-Jun-19 15:41:23 - Creating Excel...
26-Jun-19 15:41:38 - Sending Email...
26-Jun-19 15:41:48 - (535, b'5.7.3 Authentication unsuccessful [BN8PR15CA0012.namprd15.prod.outlook.com]')
Traceback (most recent call last):
  File "D:/Users/User/PycharmProjects/Scheduler/venv/FailedOrder.py", line 82, in sendEmail
    server.login(sender_email, password)
  File "D:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 730, in login
    raise last_exception
  File "D:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "D:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.3 Authentication unsuccessful [BN8PR15CA0012.namprd15.prod.outlook.com]')
26-Jun-19 15:41:48 - Job Completed
26-Jun-19 15:42:48 - Job Started
26-Jun-19 15:42:48 - Creating Excel...
26-Jun-19 15:43:02 - Sending Email...
